apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sykepenger-dashboard
  namespace: default
  labels:
    team: tbd
spec:
  image: is_set_from_pipeline
  port: 8080
  liveness:
    path: sykepenger-dashboard/
    initialDelay: 1
  readiness:
    path: sykepenger-dashboard/
    initialDelay: 1
  replicas:
    min: 1
    max: 1
  ingresses:
    - "https://sykepenger-dashboard.nais.oera.no"
    - "https://sykepenger-dashboard.prod-sbs.nais.io"
    - "https://tjenester.nav.no/sykepenger-dashboard"

